### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "a92d9dfb6708d80b63fac8975dee1153a724681b";
          sha256 = "190l9jmwk94wb26c9pyf8zdzivnx17cv8vlarfyhwbrk1znpsb22";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.14.1";
  selection = 
  {
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base-bigarray = 
    {
      pname = "base-bigarray";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bigarray/base-bigarray.base";
        hash = "sha256:1hgfwxh4vdv21m2a4g506y27pcv912v67qi4svrn53rgc43ckv6b";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    camlp-streams = 
    {
      pname = "camlp-streams";
      version = "5.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz";
        sha256 = "196rn0z2q53f8is5bwln1n5qzipn5bg3wnflnmzlxfz90qjgcwdd";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlp-streams/camlp-streams.5.0.1";
        hash = "sha256:177a68cgm23pryyji88dvn300qz55sl154wfwmzvp8arhs7yg6bn";
      };
    };
    chrome-trace = 
    {
      pname = "chrome-trace";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/chrome-trace/chrome-trace.3.14.2";
        hash = "sha256:0mqcq9j27m37gwq96qyj58zq02qmjcfbiqpfn9kl2ip3kamsljb3";
      };
    };
    conf-gmp = 
    {
      pname = "conf-gmp";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp/conf-gmp.4";
        hash = "sha256:0n7cazhsgifli8055ylnzcwd716h6x3nx9f3rr2807xj47rfvy0l";
      };
      buildInputs = [ (pkgs.gmp) ];
    };
    conf-gmp-powm-sec = 
    {
      pname = "conf-gmp-powm-sec";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.3";
        hash = "sha256:1q9c4av0ah791sq81yva4ga1mz5380r4260bjh060d3mzci00hd3";
      };
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "3";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.3";
        hash = "sha256:1k66rzbfc38k38wpzq6qp0072x3lmjv47b7jxshmhi9y76q0lawh";
      };
      buildInputs = [ (pkgs.pkg-config) ];
    };
    conf-python-3 = 
    {
      pname = "conf-python-3";
      version = "9.0.0";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-python-3/conf-python-3.9.0.0";
        hash = "sha256:03gbdbwmy3bax7q81dbanfy6mxsmnz05ky7h2qm1g5gjmm8i2bvl";
      };
      buildInputs = [ (pkgs.python3) ];
    };
    conf-zlib = 
    {
      pname = "conf-zlib";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-zlib/conf-zlib.1";
        hash = "sha256:0bsrxhap7590sk1kpwdlr1n01186135j2jd7yd35wzy06f7x5anv";
      };
      buildInputs = [ (pkgs.zlib) ];
    };
    containers = 
    {
      pname = "containers";
      version = "3.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/ocaml-containers/releases/download/v3.13.1/containers-3.13.1.tbz";
        sha256 = "114pcswmscbh5mvniiarbk5jqma3kjs6w9bx2p2lzw1w5kmjd6zb";
      };
      opamInputs = 
      {
        inherit (selection) ocaml either dune-configurator
        dune;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/containers/containers.3.13.1";
        hash = "sha256:0qljvxcnpgyxsccjmlp315g77nb7sp7iv00p74sw3qr2314vmrgn";
      };
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.9.tar.gz";
        sha256 = "0sm2vn5y7w7fyrwkv7f86y4nvs5vsrqy1x2nidy0lcqxq62ns0qn";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.9";
        hash = "sha256:19i6yqv9lq09v3xw1sfqayh40sihhd4hfyvk9dwz1m5dv1g63xlp";
      };
    };
    cryptokit = 
    {
      pname = "cryptokit";
      version = "1.19";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/xavierleroy/cryptokit/archive/release119.tar.gz";
        sha256 = "1cfc2by1df6hcxkz1yjb106nzx70r11p4pnczckgm1pvqym07qm7";
      };
      opamInputs = 
      {
        inherit (selection) zarith ocaml dune-configurator dune conf-zlib
        conf-gmp-powm-sec;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cryptokit/cryptokit.1.19";
        hash = "sha256:00c9j5s2hj7cbmnadhzzbyydwjwsz9z9bk6cbzfw2mg6rmc1z1ak";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz";
        sha256 = "1zw7fxlhx5mnf09mrhzk0yf3m4bpiii51194j0cs8ya3pc2ds50s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.2";
        hash = "sha256:1j22xbli4h2ni6y2a6ghfzdnwx0z5x1nw57hr6nmsdk0ys04a0gs";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.14.2";
        hash = "sha256:04m2slbrrz471qfi1zds89k02q0a4ka6jsas5prw8bjh2yn77g3h";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.14.2";
        hash = "sha256:1rywdkjcgi56an7a932mhlhw8m2dwlnq647rl1rzjf451hr6sfvg";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.14.2";
        hash = "sha256:06hqqcs8xvzicmvnll8bzm4ww4k2d7hcxdjs6hc3ki7495cx978q";
      };
    };
    dune-rpc = 
    {
      pname = "dune-rpc";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) xdg stdune pp ordering dyn dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-rpc/dune-rpc.3.14.2";
        hash = "sha256:1fj4pkc675pah5wxjfpwm3hb7bvw1n58dwi874hyjxixaxwbxpvm";
      };
    };
    dyn = 
    {
      pname = "dyn";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dyn/dyn.3.14.2";
        hash = "sha256:07z7y3qjwlnhh6nly0miygfkficrch958zmcwmdql148w5715q4q";
      };
    };
    either = 
    {
      pname = "either";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/either/releases/download/1.0.0/either-1.0.0.tbz";
        sha256 = "112qa1zdkf4mvn6932jb2rwxdcvfm7lg2zgh2mr7pvid67ilsrxz";
      };
      opamInputs = {
                     inherit (selection) dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/either/either.1.0.0";
        hash = "sha256:1qcj3zl0hjlc4djn5q6qjiagm5xq1q1vgbshwlf4gj7h7kzx11bf";
      };
    };
    extlib = 
    {
      pname = "extlib";
      version = "1.7.9";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ygrek/ocaml-extlib/releases/download/1.7.9/extlib-1.7.9.tar.gz";
        sha256 = "1jydzw2n84cfiz9y6lk4gih4wbr8jybanmiryfs01svd07g4vpjq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/extlib/extlib.1.7.9";
        hash = "sha256:0ms1f9ql8p3n6m81k3hc7xpid0cz2i4f0bpag6gixpmr06qw6inw";
      };
    };
    extunix = 
    {
      pname = "extunix";
      version = "0.4.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ygrek/extunix/releases/download/v0.4.1/extunix-0.4.1.tbz";
        sha256 = "0fgzvnw49c4c7mqx6wasckh5vajrws3qmygj2ry3ls134h06q7qa";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune-configurator dune base-unix
        base-bytes base-bigarray;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/extunix/extunix.0.4.1";
        hash = "sha256:08d13lzk61lp5k7d65k0fapjmyldajl95sp7w47pyjaw3snzp0y7";
      };
      buildInputs = [ (pkgs.libexecinfo-dev or null) ];
    };
    fiber = 
    {
      pname = "fiber";
      version = "3.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/fiber/releases/download/3.7.0/fiber-lwt-3.7.0.tbz";
        sha256 = "10ln7cf7l3nc43ji8iwwh9i3p4d355s8hdnfk4lr9rizx5da2j46";
      };
      opamInputs = 
      {
        inherit (selection) stdune ocaml dyn dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fiber/fiber.3.7.0";
        hash = "sha256:1ib8xwv8b31wddy63zrbby7hylc7kwlijrxq9gggn0720jkr02y6";
      };
    };
    gup = 
    {
      pname = "gup";
      version = "development";
      src = self.directSrc "gup";
      opamInputs = 
      {
        inherit (selection) ppx_deriving_protobuf oseq ocamlfind num lwt_ppx
        lwt logs extunix extlib dune cryptokit containers conf-python-3;
      };
      opamSrc = "gup.opam";
      buildInputs = [ (pkgs.zlib or null) ];
    };
    lambda-term = 
    {
      pname = "lambda-term";
      version = "3.3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/lambda-term/archive/refs/tags/3.3.2.tar.gz";
        sha256 = "0jamxgzjy74j2b8jrs1jgrn6vm63nnvzir7hj9hwaynv4dnzai1d";
      };
      opamInputs = 
      {
        inherit (selection) zed react ocaml mew_vi lwt_react lwt logs dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambda-term/lambda-term.3.3.2";
        hash = "sha256:13w19dgjfp148bc857snrvy5pnvd2czwv1jh89dxry52ddswl5xp";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz";
        sha256 = "11dpr0aprqqjgb2n4j4czpw3l0bc8dzy1jqmp2qz3xkih31k241p";
      };
      opamInputs = 
      {
        inherit (selection) ocplib-endian ocaml dune-configurator dune
        cppo;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.7.0";
        hash = "sha256:1fpvcmvrkwaz6w5rshgpw37n10dz9js68i553mmjs1g2g6wdpq73";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.1.0";
        hash = "sha256:09kc2bwmqq41983xivild7az3s62nrhp62iinvc2b6lpcldzvqqc";
      };
    };
    lwt_react = 
    {
      pname = "lwt_react";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz";
        sha256 = "1qg5wjlmrnd295lljncr1db1rw50pr13wmak3rcg92n9wd1fzm0v";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml lwt dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_react/lwt_react.1.2.0";
        hash = "sha256:0nar357nms1b90rr0iy2pa0m982yibwkbnx71hsz2v16kj9n831g";
      };
    };
    merlin-lib = 
    {
      pname = "merlin-lib";
      version = "4.14-414";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/merlin/releases/download/v4.14-414/merlin-4.14-414.tbz";
        sha256 = "0gcrfgcp4m0wk1i3ci423qdn83a2qf5zfp2dbkfh25bwlg58q0br";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/merlin-lib/merlin-lib.4.14-414";
        hash = "sha256:0fcppr5p8dd7mwpa11c352d8b5ia1fqhb92ndi1ppv05rp209zzs";
      };
    };
    mew = 
    {
      pname = "mew";
      version = "0.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew/archive/0.1.0.tar.gz";
        sha256 = "1rjri9mgfb9gn9fmjn0ax21y9jd9wkvr7mmx2jrlqmzgabmqrlv4";
      };
      opamInputs = 
      {
        inherit (selection) trie result ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew/mew.0.1.0";
        hash = "sha256:0g9xms016f909fzbwgxcy0k4xmvr5zk5bhnz66v9vpsiak2qm4s3";
      };
    };
    mew_vi = 
    {
      pname = "mew_vi";
      version = "0.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/mew_vi/archive/0.5.0.tar.gz";
        sha256 = "1nmg3cysglgw4115n5zpz4azrfbnfxkn2kvw73chzs69viygm4m6";
      };
      opamInputs = 
      {
        inherit (selection) react ocaml mew dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mew_vi/mew_vi.0.5.0";
        hash = "sha256:0zsfhxpff78cqk2c81parajb59m7hqf6v8arksxbyfha6mls65hz";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.5.tar.gz";
        sha256 = "16lm2l2j7wmxsz2nb4x1jvjjm48r4ypxqqla032xzqh1as7prq3s";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.5";
        hash = "sha256:06zrv1r5qn3hl9mpbhkbfckhhk6kysnkl348drvj3dmcg89hgnp8";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.14.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.14.1";
        hash = "sha256:16yvyr4nxcpvqp8w7wfhh9rkg2hl4ck3f64fw8kkgx7w2crcp8di";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.14.1.tar.gz";
        sha256 = "0a5h8m8jliw0pf9xwbsnhp534x2qirc1qf3lkmnzpg5ry3k0cq3p";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.14.1";
        hash = "sha256:1kpxp8pd4qw0imw3yxqk2m7fchb12b90nxgmqafha8f77qg6a0jw";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1rn7ai9n2g5xja553qa5r9iamsqmrsnl4h7zkmmbcn27qj7vczsv";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-lsp-server = 
    {
      pname = "ocaml-lsp-server";
      version = "1.17.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-lsp/releases/download/1.17.0/lsp-1.17.0.tbz";
        sha256 = "004ns7a5krka47ychk8kl7ihs3k6bc85hd6qnh42dzgf2zbvpf4g";
      };
      opamInputs = 
      {
        inherit (selection) yojson xdg uutf stdune spawn re
        ppx_yojson_conv_lib pp ordering ocamlformat-rpc-lib ocamlc-loc ocaml
        merlin-lib fiber dyn dune-rpc dune-build-info dune csexp chrome-trace
        camlp-streams astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-lsp-server/ocaml-lsp-server.1.17.0";
        hash = "sha256:116a3vc8xl5ds1ias5b8kzadrgs3dyvgx6s2q5422zhlzpxy86w7";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.3.tar.gz";
        sha256 = "1qf21zds8f3izbb9bxwblijgb7wqkrhbl99z1gpcdas147yin5ff";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.3";
        hash = "sha256:0ymzb8ykkbvpzp8swdssr1iw85a0i66vprnxsxy6dpghhpm1rrqs";
      };
    };
    ocamlc-loc = 
    {
      pname = "ocamlc-loc";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dyn dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlc-loc/ocamlc-loc.3.14.2";
        hash = "sha256:01pk3knfrq1q1nzq09kfpy6aza6x4xvgwrpgg8kic35153h3h0gw";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.6";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.6.tar.gz";
        sha256 = "18ih56m5z13z5zla7wdrin4y1bdz7pwpjn7znmnn0sz1k8krdy9d";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.6";
        hash = "sha256:1qs30vvj6mbrrgaxy54kw8zqqghxaywygyhspzhpdkwkl98j3y76";
      };
    };
    ocamlformat-rpc-lib = 
    {
      pname = "ocamlformat-rpc-lib";
      version = "0.26.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocamlformat/releases/download/0.26.1/ocamlformat-0.26.1.tbz";
        sha256 = "1my6fh6sfispalyypar5xv1vgncvb53d825q5xhyrf8mgx16w06s";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlformat-rpc-lib/ocamlformat-rpc-lib.0.26.1";
        hash = "sha256:01i7s0xrmnn1mpfj6lbwsm1g33q68hm1p8kcd3l5j6n8nnjpcwdv";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    ordering = 
    {
      pname = "ordering";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ordering/ordering.3.14.2";
        hash = "sha256:1wmk0b8ywjpyv1n4h8f2ly0gbii4xf7z563jp49gwdsliyl5v4y1";
      };
    };
    oseq = 
    {
      pname = "oseq";
      version = "0.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/c-cube/oseq/releases/download/v0.5.1/oseq-0.5.1.tbz";
        sha256 = "1dgylqszxyl41n08687zi8b02m3xi2dm1p44d9c9k2wyg9fnshi5";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/oseq/oseq.0.5.1";
        hash = "sha256:03ywnpq4fflh0ampdkc9lws3n9lk1n9r1g66hbp793dggp0l9cmk";
      };
    };
    ounit = 
    {
      pname = "ounit";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = {
                     inherit (selection) ounit2 ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit/ounit.2.2.7";
        hash = "sha256:15jq26fb0mcgm2hpm6av39ig5kyvngqkbk52hwg45n7arfbck455";
      };
    };
    ounit2 = 
    {
      pname = "ounit2";
      version = "2.2.7";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gildor478/ounit/releases/download/v2.2.7/ounit-2.2.7.tbz";
        sha256 = "123k1qy62p4gicixdgbna85y176pkc2j5xxjp7c522i4s4xydxlh";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims seq ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ounit2/ounit2.2.2.7";
        hash = "sha256:1bm5vvfyvb2bdjiqih1rxjn3j3qxk7ls83lr65qh0abjiws6s8zj";
      };
    };
    pp = 
    {
      pname = "pp";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/pp/releases/download/1.2.0/pp-1.2.0.tbz";
        sha256 = "174hwr63gpliw9w2ipzjbkvdib7js6n6xicyn8nv9bsm7ibj5s55";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pp/pp.1.2.0";
        hash = "sha256:01jdpmgn5pagfax63y23z532xl8s2sb6wpcn96fh612azk1fm5li";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_deriving = 
    {
      pname = "ppx_deriving";
      version = "5.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_deriving/releases/download/v5.2.1/ppx_deriving-v5.2.1.tbz";
        sha256 = "11h75dsbv3rs03pl67hdd3lbim7wjzh257ij9c75fcknbfr5ysz9";
      };
      opamInputs = 
      {
        inherit (selection) result ppxlib ppx_derivers ocamlfind ocaml dune
        cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_deriving/ppx_deriving.5.2.1";
        hash = "sha256:04nkhnjvj4zgd45y3b67sqs9dh4vv0maz3y07h9j509v3k9rldad";
      };
    };
    ppx_deriving_protobuf = 
    {
      pname = "ppx_deriving_protobuf";
      version = "3.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_deriving_protobuf/releases/download/v3.0.0/ppx_deriving_protobuf-v3.0.0.tbz";
        sha256 = "1dc1vxnkd0cnrgac5v3zbaj2lq1d2w8118mp1cmsdxylp06yz1sj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_deriving ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_deriving_protobuf/ppx_deriving_protobuf.3.0.0";
        hash = "sha256:1hd9qbm7r17zjrd5p4zh0swq71pz00fas82qg8v586a5qz1hbf9b";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/ppx_yojson_conv_lib-v0.16.0.tar.gz";
        sha256 = "0zgchrn9w5h2bg2rnrmhfscpnkf5xhg9z02da6xlqnrnip446z2m";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.16.0";
        hash = "sha256:1p87jf31aq4jkwzb6j361jjgi26zj340623gic06pdamz2jxvrbw";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.32.1-5.2preview";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/archive/04e050cbe2cf3e5cdb4441c480e4f472a5033941.tar.gz";
        sha256 = "1nfc9ls45yk2znq43anvvv67njk74rr3d2iq7aicqaivncii3rph";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.32.1~5.2preview";
        hash = "sha256:17nh5flhc0iy4cn83nh9r843kpnvhv39na1hn7548li9vqr58pmd";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.11.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.11.0/re-1.11.0.tbz";
        sha256 = "0kwdvzb2wy3rxq3mvmsgc8cdwrzka2viysvrmrrbxxn0h13j9z01";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.11.0";
        hash = "sha256:18048c9lw3g8db1r01diljzvla2pj9bw2fcnvq34gnviwi9rxqjf";
      };
    };
    react = 
    {
      pname = "react";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/react/releases/react-1.2.2.tbz";
        sha256 = "16cg4byj8lfbbw96dhh8sks5y9n1c3fshz7f2p8m7wgisqax7bf4";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/react/react.1.2.2";
        hash = "sha256:1airidp9cw8sk92jc3bvarph3pc43qaf3hcywi0anmpznsygcm0z";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.16/files/sexplib0-v0.16.0.tar.gz";
        sha256 = "07bhj2akd6i33h11qin4wns9qnjicf871yzji7vi4i8rd1ja5nw6";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.16.0";
        hash = "sha256:11zmpbm8pj86dmc2fgbz33ngqs1a854dgsayq24hzlvdvif5bgqw";
      };
    };
    spawn = 
    {
      pname = "spawn";
      version = "v0.15.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/spawn/archive/v0.15.1.tar.gz";
        sha256 = "0l4xq43dxsvxli9kkpnywrw81dyn11bfpdlsd36kyv5b9wqyxzcs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/spawn/spawn.v0.15.1";
        hash = "sha256:18cl7lgcf5gl3r5ffdqiza5hydjgn8hwk4lsb6gsibv8jd7jx8bq";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stdune = 
    {
      pname = "stdune";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = 
      {
        inherit (selection) pp ordering ocaml dyn dune csexp base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdune/stdune.3.14.2";
        hash = "sha256:0lf9d9apcv90ynpb73fy7av2zd9kmbi0z6386gcdlv1ch2dj8k9r";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.7";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz";
        sha256 = "06dya9n5im3dbqqv4l6yssi8siw111c1hp94n5y14vddyg9jmhjz";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.7";
        hash = "sha256:1411142m653308lj3nlgbv2wvww2i5hyfdgz94l2b3ga3qdp7szc";
      };
    };
    trie = 
    {
      pname = "trie";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/kandu/trie/archive/1.0.0.tar.gz";
        sha256 = "1slq4kiwnc723dsaw15ms7xxpqz061v8zck1m6iyc5j2li70by62";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/trie/trie.1.0.0";
        hash = "sha256:1ds07ikjjymacnlxfx1widfi7qz0js61lsqqq0xa90501p17nq10";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    utop = 
    {
      pname = "utop";
      version = "2.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/utop/releases/download/2.14.0/utop-2.14.0.tbz";
        sha256 = "1a9v4w6nw8dp30qk1bkk6vhpp6vgs46gx8b32jkj91a5bfyakm8g";
      };
      opamInputs = 
      {
        inherit (selection) zed xdg react ocamlfind ocaml lwt_react lwt logs
        lambda-term dune cppo base-unix base-threads;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/utop/utop.2.14.0";
        hash = "sha256:1x2f0nl0rah8cixal8lm2fckl4416pbpllv45fv4f1l6abz6immr";
      };
    };
    uucp = 
    {
      pname = "uucp";
      version = "15.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uucp/releases/uucp-15.1.0.tbz";
        sha256 = "11srn8zwba31zmj129v6l8sigdm9qrgcfd59vl1qmds70s44n7m9";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        uunf = selection.uunf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uucp/uucp.15.1.0";
        hash = "sha256:1j03ndh8rqnyw2wzxsvkgxcirh5anp6d9pvp6kgijz9d0dwzr2i6";
      };
    };
    uuseg = 
    {
      pname = "uuseg";
      version = "15.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uuseg/releases/uuseg-15.1.0.tbz";
        sha256 = "1ial0afpc02ih73ad7136gv3dsz26h3p51pbkzw3a7vmvrckgwi0";
      };
      opamInputs = 
      {
        inherit (selection) uucp topkg ocamlfind ocamlbuild
        ocaml;
        uutf = selection.uutf or null;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuseg/uuseg.15.1.0";
        hash = "sha256:02w89ljiiaidlajbc47ri6wbkqpbazvqqz73pb0qxj4wfd51vzdb";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    xdg = 
    {
      pname = "xdg";
      version = "3.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.14.2/dune-3.14.2.tbz";
        sha256 = "1qdcwsscdam09hb836s5ykdg32prh8lspjz0v7clj9rb6v5nf278";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xdg/xdg.3.14.2";
        hash = "sha256:1qmqx47kba7cy4qgwv05n2khz8vn62ljpzm4pnznzwfwblgf8f24";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "2.1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/2.1.2/yojson-2.1.2.tbz";
        sha256 = "1ydlvw0f50vg8ia9529ldq07d2jyqzjr9230pyywr9y8pymz3wjr";
      };
      opamInputs = 
      {
        inherit (selection) seq ocaml dune cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.2.1.2";
        hash = "sha256:10cqyg4ykrfc39lfb0xhykknym1pz5saivq3ighgns4a1rnkixf3";
      };
    };
    zarith = 
    {
      pname = "zarith";
      version = "1.13";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/Zarith/archive/release-1.13.tar.gz";
        sha256 = "0fzqnc4h9nisszykz2fyfrwvfpq7iqymi4kgwvb3l450zqrnv0m5";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zarith/zarith.1.13";
        hash = "sha256:0k6zyd28qa6rgs3z8k1z3b8wspi5w570lkfph6z894y5n289aih4";
      };
    };
    zed = 
    {
      pname = "zed";
      version = "3.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/zed/archive/refs/tags/3.2.3.tar.gz";
        sha256 = "13057gf7z2zl4wps8mzf84pm7y52p5z0vzv9zrlp4cl2ss2k0sjb";
      };
      opamInputs = 
      {
        inherit (selection) uutf uuseg uucp uchar result react ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zed/zed.3.2.3";
        hash = "sha256:11pgssqmpr49z1ibnl2hakkdaznhna7nc2zzyhd04x94wnmmk9cm";
      };
    };
  };
}

